### ISSUE TITLE
Ways to change the dataseries name

### ISSUE THREAD

**Issue by zarelit** [bfi-de/ngsild-grafana-datasource#1]
Hello! I'm trying to create a dashboard with the number of free spots in some parking lots and came up with something like this in the picture below.

The issue is that it's only possible to select between long entity names and short entity names while I would like to name the series after the (current) name of the entity in the `name` attribute.

Is there a way to do this with the query builder somehow?

I also tried to add a second query to have the value of the names of the entities but I can't merge the results in any way.

![image](https://user-images.githubusercontent.com/3449926/226975755-2461b2db-c7a6-4fd1-bc51-37f3e5bb7ae7.png)

**Comment by cnoelle** [comment]
Hi, I just pushed a commit that should enable this feature. You can now select:
* Naming pattern: Entity
* Entity name: name
These options replace the checkbox "Long entity names" and allow for more flexible configurations.

**Comment by zarelit** [comment]
Thank you very much @cnoelle !
