### ISSUE TITLE
The **Authentication active?** option is ignored when not using the proxy

### ISSUE THREAD

**Issue by pierre-josselin** [bfi-de/ngsild-grafana-datasource#3]
Hi,

I noticed that the **Authentication active?** option is ignored when not using the proxy.

![image](https://github.com/bfi-de/ngsild-grafana-datasource/assets/70814177/b363d53c-0851-492d-99f2-8441a94accc3)

Yet when Grafana attempts to access the data, it connect directly to the context broker without first requesting an access token, which generates the following error:

![image](https://github.com/bfi-de/ngsild-grafana-datasource/assets/70814177/d5ac8097-8785-474e-8fea-ff3be581bfe4)

It works correctly when using the proxy mode.

This isn't necessarily a problem and seems logical from a security perspective, but perhaps it would be better to make it impossible to configure authentication if direct mode is selected?

**Comment by cnoelle** [comment]
Yes, it only works in proxy mode, and yes, for direct mode it should not be possible to activate authentication in the config editor.

The plugin uses the built-in Grafana OAuth capability described here: https://grafana.com/developers/plugin-tools/create-a-plugin/extend-a-plugin/add-authentication-for-data-source-plugins#add-an-oauth-20-proxy-route-to-your-plugin. It is not available in direct mode.

**Comment by pierre-josselin** [comment]
Thank you for the details
