### ISSUE TITLE
Multi-Tenant Support

### ISSUE THREAD

**Issue by fbuedding** [bfi-de/ngsild-grafana-datasource#7]
Since Orion-LD, Scorpio and Stellio are supporting multi-tenancy and the iot-agents need it to work correctly, it would be good to define at least "NGSILD-Tenant" on the datasource level.

Maybe also the NGSILD-Path on request level.

PS: I don't want to seem rude with all the issues I create. I think the plugin is great and am testing whether we can use it in a research project and create an issue for everything I notice. Thank you!

**Comment by cnoelle** [comment]
> Since Orion-LD, Scorpio and Stellio are supporting multi-tenancy and the iot-agents need it to work correctly, it would be good to define at least "NGSILD-Tenant" on the datasource level.

Sounds good. If I understand it correctly, this simply requires sending the NGSILD-Tenant header with every request. I also agree to define it at the datasource level.

> 
> Maybe also the NGSILD-Path on request level.

Not sure what you mean? There is no reference to NGSILD-Path in the spec.

> 
> PS: I don't want to seem rude with all the issues I create. I think the plugin is great and am testing whether we can use it in a research project and create an issue for everything I notice. Thank you!

Sure, go ahead!

**Comment by cnoelle** [comment]
Ok, so *Path* probably refers to what is called *scope* in the latest version of the spec. In the older NGSI-v2 the two properties were called *Fiware-Service* (now header *NGSILD-Tenant*) and *Fiware-ServicePath* (now special entity attribute *scope*). *Scope* seems to be supported by the Scorpio broker but not by Orion-LD, based on these issues:

* https://github.com/ScorpioBroker/ScorpioBroker/issues/503
* https://github.com/FIWARE/context.Orion-LD/issues/1610

To filter for scope one can add a parameter *scopeQ* to a query, e.g. `scopeQ="/Madrid/Centro,/Madrid/Cortes"`. 
Spec reference: [NGSILD API V1.8.1 (2024-03)](https://www.etsi.org/deliver/etsi_gs/CIM/001_099/009/01.08.01_60/gs_cim009v010801p.pdf)

**Comment by cnoelle** [comment]
Available in v1.1.2
