### ISSUE TITLE
Temporal query with entity id errors

### ISSUE THREAD

**Issue by fbuedding** [bfi-de/ngsild-grafana-datasource#9]
When performing a temporal query with an entity id the following error occurs with Scorpio:
Error:
```json
    "type": "https://uri.etsi.org/ngsi-ld/errors/BadRequestData",
    "title": "Bad Request Data.",
    "detail": "id is not a URI",
    "status": 400
````	

The code suggest this is a known error: https://github.com/bfi-de/ngsild-grafana-datasource/blob/54c66aacbf3ca071879f8450fad67142cf5ceb32/datasource/plugin/src/datasource.ts#L228

Fixed accordingly in Pull request: https://github.com/bfi-de/ngsild-grafana-datasource/pull/8

**Comment by cnoelle** [comment]
Merged in v1.2.1
